import sourceRegistry from "@/content/clinical-images/source-registry.json"

import type { ClinicalImageMeta, ClinicalImageSourceRegistryEntry } from "@/content/clinical-images/types"

export const clinicalImageSourceRegistry =
  sourceRegistry as ClinicalImageSourceRegistryEntry[]

export const clinicalImageManifest: ClinicalImageMeta[] = [
  {
    id: "acne_placeholder_face",
    disease: "acne",
    title: "痤疮演示占位",
    sourceId: "cdc-phil",
    source: "CDC PHIL",
    sourceUrl: "https://wwwn.cdc.gov/phil/default.aspx",
    usagePermissionNote: "当前仅为目录与字段占位，未落真实图片。",
    bodyPart: "face",
    severity: "mild",
    displayNote: "用于验证后续知识页或病例图片区块结构。",
    summary: "轻度面部痤疮的占位条目。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["acne", "placeholder", "face"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["acne", "integrated-acne"],
    updatedAt: "2026-04-12"
  },
  {
    id: "eczema_placeholder_arm",
    disease: "dermatitis",
    title: "湿疹演示占位",
    sourceId: "dermnet",
    source: "DermNet NZ",
    sourceUrl: "https://dermnetnz.org/image-catalogue",
    usagePermissionNote: "当前仅为目录与字段占位，未落真实图片。",
    bodyPart: "arm",
    severity: "moderate",
    displayNote: "用于验证湿疹类图片条目结构。",
    summary: "湿疹条目的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["eczema", "placeholder", "arm"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["eczema", "dermatitis", "integrated-eczema"],
    updatedAt: "2026-04-12"
  },
  {
    id: "dermatitis_placeholder_hand",
    disease: "dermatitis",
    title: "皮炎演示占位",
    sourceId: "hse-skin-library",
    source: "HSE Skin Library",
    sourceUrl: "https://www.hse.gov.uk/skin/imagelibrary.htm",
    usagePermissionNote: "当前仅为结构占位，未落真实图片。",
    bodyPart: "hand",
    severity: "moderate",
    displayNote: "用于接触性皮炎或刺激性皮炎条目结构展示。",
    summary: "皮炎类问题的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["dermatitis", "placeholder", "hand"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["dermatitis", "contact-dermatitis"],
    updatedAt: "2026-04-12"
  },
  {
    id: "psoriasis_placeholder_elbow",
    disease: "psoriasis",
    title: "银屑病演示占位",
    sourceId: "dermnet",
    source: "DermNet NZ",
    sourceUrl: "https://dermnetnz.org/image-catalogue",
    usagePermissionNote: "当前仅为目录与字段占位，未落真实图片。",
    bodyPart: "elbow",
    severity: "moderate",
    displayNote: "用于验证银屑病条目结构。",
    summary: "银屑病条目的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["psoriasis", "placeholder", "elbow"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: [],
    updatedAt: "2026-04-12"
  },
  {
    id: "rosacea_placeholder_face",
    disease: "rosacea",
    title: "面部泛红演示占位",
    sourceId: "dermnet",
    source: "DermNet NZ",
    sourceUrl: "https://dermnetnz.org/image-catalogue",
    usagePermissionNote: "当前仅为结构占位，未落真实图片。",
    bodyPart: "face",
    severity: "moderate",
    displayNote: "用于酒糟鼻和面部潮红条目结构展示。",
    summary: "面部泛红类问题的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["rosacea", "placeholder", "face"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["rosacea"],
    updatedAt: "2026-04-12"
  },
  {
    id: "fungal_placeholder_foot",
    disease: "fungal",
    title: "真菌感染演示占位",
    sourceId: "cdc-phil",
    source: "CDC PHIL",
    sourceUrl: "https://wwwn.cdc.gov/phil/default.aspx",
    usagePermissionNote: "当前仅为目录与字段占位，未落真实图片。",
    bodyPart: "foot",
    severity: "unknown",
    displayNote: "用于验证真菌感染类占位结构。",
    summary: "真菌感染条目的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["fungal", "placeholder", "foot"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: [],
    updatedAt: "2026-04-12"
  },
  {
    id: "urticaria_placeholder_torso",
    disease: "urticaria",
    title: "荨麻疹演示占位",
    sourceId: "hse-skin-library",
    source: "HSE Skin Library",
    sourceUrl: "https://www.hse.gov.uk/skin/imagelibrary.htm",
    usagePermissionNote: "当前仅为结构占位，未落真实图片。",
    bodyPart: "torso",
    severity: "moderate",
    displayNote: "用于荨麻疹和风团条目结构展示。",
    summary: "风团样皮损的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["urticaria", "placeholder", "torso"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["urticaria"],
    updatedAt: "2026-04-12"
  },
  {
    id: "dry_skin_placeholder_leg",
    disease: "dry-skin",
    title: "干燥起皮演示占位",
    sourceId: "dermnet",
    source: "DermNet NZ",
    sourceUrl: "https://dermnetnz.org/image-catalogue",
    usagePermissionNote: "当前仅为结构占位，未落真实图片。",
    bodyPart: "leg",
    severity: "mild",
    displayNote: "用于干燥起皮和敏感肌护理条目结构展示。",
    summary: "干燥脱屑类问题的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["dry-skin", "placeholder", "leg"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["dry-skin-care", "sensitive-skin-care"],
    updatedAt: "2026-04-12"
  }
]
