import sourceRegistry from "@/content/clinical-images/source-registry.json"

import type { ClinicalImageMeta, ClinicalImageSourceRegistryEntry } from "@/content/clinical-images/types"

export const clinicalImageSourceRegistry =
  sourceRegistry as ClinicalImageSourceRegistryEntry[]

export const clinicalImageManifest: ClinicalImageMeta[] = [
  {
    id: "cdc_phil_4506_atopic_dermatitis_arm",
    disease: "dermatitis",
    title: "特应性皮炎病例图",
    sourceId: "cdc-phil",
    source: "CDC PHIL",
    sourceUrl: "https://phil.cdc.gov/Details.aspx?pid=4506",
    usagePermissionNote:
      "来自 CDC Public Health Image Library。已按答辩演示用途接入 lores 图，仅用于知识页展示与本地演示，不默认进入自动分析数据集。",
    bodyPart: "arm",
    severity: "moderate",
    displayNote: "用于湿疹 / 皮炎知识页的正式演示样例。",
    summary: "前臂大片脱屑样皮损，可用于演示湿疹与皮炎类知识卡的图文对应关系。",
    path: "/clinical-images/demo/eczema-dermatitis/cdc-phil-4506-eczema.jpg",
    status: "approved",
    placeholder: false,
    tags: ["dermatitis", "eczema", "arm", "cdc-phil"],
    copyrightStatus: "approved-for-demo",
    usageScope: "knowledge-page-only",
    relatedKnowledgeEntryIds: ["eczema", "dermatitis", "integrated-eczema"],
    updatedAt: "2026-04-15",
  },
  {
    id: "cdc_phil_4811_tinea_corporis_forearm",
    disease: "fungal",
    title: "体癣病例图",
    sourceId: "cdc-phil",
    source: "CDC PHIL",
    sourceUrl: "https://phil.cdc.gov/Details.aspx?pid=4811",
    usagePermissionNote:
      "来自 CDC Public Health Image Library。已按答辩演示用途接入 lores 图，仅用于知识页展示与本地演示，不默认进入自动分析数据集。",
    bodyPart: "forearm",
    severity: "mild",
    displayNote: "用于真菌感染知识页和图片问诊演示的正式样例。",
    summary: "前臂环形红斑样皮损，适合对应体癣 / 浅表真菌感染的演示讲解。",
    path: "/clinical-images/demo/fungal/cdc-phil-4811-ringworm.jpg",
    status: "approved",
    placeholder: false,
    tags: ["fungal", "ringworm", "tinea-corporis", "forearm", "cdc-phil"],
    copyrightStatus: "approved-for-demo",
    usageScope: "knowledge-page-only",
    relatedKnowledgeEntryIds: ["tinea-corporis"],
    updatedAt: "2026-04-15",
  },
  {
    id: "cdc_phil_17271_tinea_barbae_chin",
    disease: "fungal",
    title: "须癣病例图",
    sourceId: "cdc-phil",
    source: "CDC PHIL",
    sourceUrl: "https://phil.cdc.gov/Details.aspx?pid=17271",
    usagePermissionNote:
      "来自 CDC Public Health Image Library。已按答辩演示用途接入 lores 图，仅用于知识页展示与本地演示，不默认进入自动分析数据集。",
    bodyPart: "chin",
    severity: "moderate",
    displayNote: "用于补充展示面颈部真菌感染样例，方便区分与单纯毛囊炎。",
    summary: "下颌须区片状鳞屑与炎症改变，可用于演示须癣这类毛发区真菌感染。",
    path: "/clinical-images/demo/fungal/cdc-phil-17271-tinea-barbae.jpg",
    status: "approved",
    placeholder: false,
    tags: ["fungal", "tinea-barbae", "beard", "chin", "cdc-phil"],
    copyrightStatus: "approved-for-demo",
    usageScope: "knowledge-page-only",
    relatedKnowledgeEntryIds: ["tinea-corporis"],
    updatedAt: "2026-04-15",
  },
  {
    id: "acne_placeholder_face",
    disease: "acne",
    title: "痤疮演示占位",
    sourceId: "cdc-phil",
    source: "CDC PHIL",
    sourceUrl: "https://wwwn.cdc.gov/phil/default.aspx",
    usagePermissionNote: "当前仅保留目录与字段占位，尚未接入正式图片。",
    bodyPart: "face",
    severity: "mild",
    displayNote: "用于验证后续痤疮类病例图条目结构。",
    summary: "轻度面部痤疮的占位条目。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["acne", "placeholder", "face"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["acne", "integrated-acne"],
    updatedAt: "2026-04-12",
  },
  {
    id: "psoriasis_placeholder_elbow",
    disease: "psoriasis",
    title: "银屑病演示占位",
    sourceId: "dermnet",
    source: "DermNet NZ",
    sourceUrl: "https://dermnetnz.org/image-catalogue",
    usagePermissionNote: "当前仅保留目录与字段占位，尚未接入正式图片。",
    bodyPart: "elbow",
    severity: "moderate",
    displayNote: "用于验证银屑病病例图条目结构。",
    summary: "银屑病条目的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["psoriasis", "placeholder", "elbow"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["psoriasis"],
    updatedAt: "2026-04-12",
  },
  {
    id: "rosacea_placeholder_face",
    disease: "rosacea",
    title: "面部泛红演示占位",
    sourceId: "dermnet",
    source: "DermNet NZ",
    sourceUrl: "https://dermnetnz.org/image-catalogue",
    usagePermissionNote: "当前仅保留结构占位，尚未接入正式图片。",
    bodyPart: "face",
    severity: "moderate",
    displayNote: "用于酒糟鼻和面部潮红条目结构展示。",
    summary: "面部泛红类问题的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["rosacea", "placeholder", "face"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["rosacea"],
    updatedAt: "2026-04-12",
  },
  {
    id: "urticaria_placeholder_torso",
    disease: "urticaria",
    title: "荨麻疹演示占位",
    sourceId: "hse-skin-library",
    source: "HSE Skin Library",
    sourceUrl: "https://www.hse.gov.uk/skin/imagelibrary.htm",
    usagePermissionNote: "当前仅保留结构占位，尚未接入正式图片。",
    bodyPart: "torso",
    severity: "moderate",
    displayNote: "用于荨麻疹和风团条目结构展示。",
    summary: "风团样皮损的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["urticaria", "placeholder", "torso"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["urticaria"],
    updatedAt: "2026-04-12",
  },
  {
    id: "dry_skin_placeholder_leg",
    disease: "dry-skin",
    title: "干燥起皮演示占位",
    sourceId: "dermnet",
    source: "DermNet NZ",
    sourceUrl: "https://dermnetnz.org/image-catalogue",
    usagePermissionNote: "当前仅保留结构占位，尚未接入正式图片。",
    bodyPart: "leg",
    severity: "mild",
    displayNote: "用于干燥起皮和敏感肌护理条目结构展示。",
    summary: "干燥脱屑类问题的占位示例。",
    path: null,
    status: "placeholder",
    placeholder: true,
    tags: ["dry-skin", "placeholder", "leg"],
    copyrightStatus: "requires-review",
    usageScope: "placeholder-only",
    relatedKnowledgeEntryIds: ["dry-skin-care", "sensitive-skin-care"],
    updatedAt: "2026-04-12",
  },
]
