export const curatedModels = [
  {
    id: "gpt-5.4-mini",
    providerId: "openai",
    apiFormat: "openai-responses",
    modelId: "gpt-5.4-mini",
    displayName: "GPT-5.4 mini",
    name: "GPT-5.4 mini",
    description: "适合作为稳妥的文本备选，不作为普通用户的默认入口。",
    summary: "通用文本与轻推理的平衡选择",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "medium",
    recommendedScore: 4.7,
    capabilities: ["通用问答", "代码", "内容整理"],
    capabilitySummary: ["通用任务平衡", "适合作为默认模型", "支持流式输出"],
    status: "unknown",
    latencyMs: null,
    networkHint: "待实测",
    recommendedUseCases: ["默认对话", "知识整理", "结构化问答"],
    sessionType: "text",
  },
  {
    id: "gpt-5.4",
    providerId: "openai",
    apiFormat: "openai-responses",
    modelId: "gpt-5.4",
    displayName: "GPT-5.4",
    name: "GPT-5.4",
    description: "适合重点展示复杂推理，不建议普通用户默认使用。",
    summary: "深度推理优先",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.6,
    capabilities: ["深度推理", "复杂任务", "高质量生成"],
    capabilitySummary: ["Responses 格式", "复杂推理更强", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["复杂诊断建议整理", "高难度推理", "重点展示场景"],
    sessionType: "text",
  },
  {
    id: "qwen-plus-latest",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen-plus-latest",
    displayName: "Qwen Plus Latest",
    name: "Qwen Plus Latest",
    description: "保留给低成本中文备选与对照测试，这轮不进入主演示文本路径。",
    summary: "中文低成本备选，不作为答辩主入口",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 3.7,
    capabilities: ["中文问答", "内容整理", "低成本"],
    capabilitySummary: ["中文友好", "成本低", "演示优先级已下调"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["成本敏感备选", "对照测试", "非主路径中文问答"],
    sessionType: "text",
  },
  {
    id: "deepseek-v3.2",
    providerId: "deepseek",
    apiFormat: "openai-chat",
    modelId: "deepseek-v3.2",
    displayName: "DeepSeek V3.2",
    name: "DeepSeek V3.2",
    description: "当前中转链路下实测可用，适合作为稳定中文文本主力之一。",
    summary: "稳定中文文本主力",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "medium",
    recommendedScore: 4.8,
    capabilities: ["中文理解", "结构化输出", "通用推理"],
    capabilitySummary: ["中文稳定", "当前链路可用", "适合主会话"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["主力中文聊天", "知识解释", "中等复杂任务"],
    sessionType: "text",
  },
  {
    id: "deepseek-chat",
    providerId: "deepseek",
    apiFormat: "openai-chat",
    modelId: "deepseek-chat",
    displayName: "DeepSeek Chat",
    name: "DeepSeek Chat",
    description: "适合作为低成本快速文本备选，不建议作为答辩默认主模型。",
    summary: "低成本通用文本",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 4.1,
    capabilities: ["通用问答", "低成本", "快速响应"],
    capabilitySummary: ["便宜", "快", "适合泛用"],
    status: "unknown",
    latencyMs: null,
    networkHint: "待实测",
    recommendedUseCases: ["成本敏感场景", "快速问答", "备用模型"],
    sessionType: "text",
  },
  {
    id: "deepseek-r1",
    providerId: "deepseek",
    apiFormat: "openai-chat",
    modelId: "deepseek-r1",
    displayName: "DeepSeek R1",
    name: "DeepSeek R1",
    description: "深度思考路线的代表模型，适合推理型问题。",
    summary: "深度推理与思考",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.8,
    capabilities: ["深度推理", "复杂分析", "思考型回答"],
    capabilitySummary: ["思考强", "复杂推理好", "速度中等"],
    status: "unknown",
    latencyMs: null,
    networkHint: "待实测",
    recommendedUseCases: ["复杂病情分析", "推理问题", "展示深度思考"],
    sessionType: "text",
  },
  {
    id: "deepseek-v3-1",
    providerId: "deepseek",
    apiFormat: "openai-chat",
    modelId: "deepseek-v3-1",
    displayName: "DeepSeek V3.1",
    name: "DeepSeek V3.1",
    description: "新版混合推理模型，适合兼顾速度、中文问诊和复杂分析。",
    summary: "新版中文推理主力",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.8,
    capabilities: ["中文问答", "混合推理", "结构化整理"],
    capabilitySummary: ["比 R1 更快", "适合中文问诊", "演示稳定性较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["中文主力问诊", "结构化分析", "复杂问题整理"],
    sessionType: "text",
  },
  {
    id: "deepseek-r1-0528",
    providerId: "deepseek",
    apiFormat: "openai-chat",
    modelId: "deepseek-r1-0528",
    displayName: "DeepSeek R1 0528",
    name: "DeepSeek R1 0528",
    description: "DeepSeek 新版深度推理模型，适合高难度皮肤问题分析。",
    summary: "新版深度推理",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.9,
    capabilities: ["深度推理", "复杂分析", "长链思考"],
    capabilitySummary: ["推理更强", "适合复杂病情分析", "延迟较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["复杂病情推理", "多步判断", "重点展示场景"],
    sessionType: "text",
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-235b-a22b-instruct-2507",
    displayName: "Qwen 3 235B Instruct",
    name: "Qwen 3 235B Instruct",
    description: "超大参数中文模型，适合高质量问答、解释和整理。",
    summary: "高质量中文文本",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.7,
    capabilities: ["高质量中文", "长文整理", "复杂解释"],
    capabilitySummary: ["中文表达好", "解释更细", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["高质量中文回答", "长文归纳", "复杂解释"],
    sessionType: "text",
  },
  {
    id: "qwen3-235b-a22b-thinking-2507",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-235b-a22b-thinking-2507",
    displayName: "Qwen 3 235B Thinking",
    name: "Qwen 3 235B Thinking",
    description: "带思考模式的中文大模型，适合推理和分步判断。",
    summary: "中文深度推理",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.8,
    capabilities: ["中文推理", "多步分析", "思考模式"],
    capabilitySummary: ["思考链更强", "适合复杂分析", "延迟较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["复杂问诊分析", "分步解释", "高难度推理"],
    sessionType: "text",
  },
  {
    id: "kimi-k2-instruct",
    providerId: "kimi",
    apiFormat: "openai-chat",
    modelId: "kimi-k2-instruct",
    displayName: "Kimi K2 Instruct",
    name: "Kimi K2 Instruct",
    description: "Kimi 指令模型，适合知识解释、整理和长上下文问答。",
    summary: "长上下文中文问答",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.6,
    capabilities: ["长上下文", "中文解释", "知识整理"],
    capabilitySummary: ["上下文长", "解释清楚", "适合知识问答"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["知识解释", "长病史整理", "中文问答"],
    sessionType: "text",
  },
  {
    id: "kimi-k2-thinking",
    providerId: "kimi",
    apiFormat: "openai-chat",
    modelId: "kimi-k2-thinking",
    displayName: "Kimi K2 Thinking",
    name: "Kimi K2 Thinking",
    description: "Kimi 思考版，更适合复杂诊断推理和分步解释。",
    summary: "Kimi 深度思考",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.7,
    capabilities: ["思考模式", "复杂推理", "长链解释"],
    capabilitySummary: ["推理更强", "适合复杂分析", "延迟较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["复杂病情分析", "分步判断", "深度思考展示"],
    sessionType: "text",
  },
  {
    id: "claude-sonnet-4-6",
    providerId: "anthropic",
    apiFormat: "openai-chat",
    modelId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    name: "Claude Sonnet 4.6",
    description: "适合高质量文本生成与解释，但默认优先级低于国内更稳的入口模型。",
    summary: "高质量综合文本",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.5,
    capabilities: ["复杂写作", "高质量表达", "推理"],
    capabilitySummary: ["高质量", "稳定", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["高质量对话", "展示性回答", "复杂解释"],
    sessionType: "text",
  },
  {
    id: "gpt-4.1",
    providerId: "openai",
    apiFormat: "openai-chat",
    modelId: "gpt-4.1",
    displayName: "GPT-4.1",
    name: "GPT-4.1",
    description: "当前中转链路下已实测可用的国外高端文本模型，中文回复稳定，适合作为国际模型对照。",
    summary: "实测可用的国外高端文本模型",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.7,
    capabilities: ["高质量问答", "结构化输出", "复杂解释"],
    capabilitySummary: ["中文输出稳定", "当前链路实测可用", "适合高质量对照"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["国际模型对照", "高质量文本问诊", "复杂建议整理"],
    sessionType: "text",
  },
  {
    id: "claude-opus-4-6-thinking",
    providerId: "anthropic",
    apiFormat: "anthropic-messages",
    modelId: "claude-opus-4-6-thinking",
    displayName: "Claude Opus 4.6 Thinking",
    name: "Claude Opus 4.6 Thinking",
    description: "Claude 原生思考版，走 messages 原生格式。",
    summary: "原生深度思考",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.9,
    capabilities: ["深度推理", "复杂任务", "长链思考"],
    capabilitySummary: ["messages 原生格式", "思考深", "成本高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["高难度分析", "深度展示", "复杂推理"],
    sessionType: "text",
  },
  {
    id: "gpt-5-all",
    providerId: "openai",
    apiFormat: "openai-chat",
    modelId: "gpt-5-all",
    displayName: "GPT-5 All",
    name: "GPT-5 All",
    description: "当前中转链路下实测可用的 OpenAI 旗舰通用模型，支持图文一体化问诊。",
    summary: "旗舰多模态通用入口",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.9,
    capabilities: ["图文联合", "复杂推理", "旗舰综合能力"],
    capabilitySummary: ["OpenAI 旗舰", "当前链路可用", "适合通用入口对比"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["通用图文问诊", "复杂病情解释", "展示型多模态对比"],
    sessionType: "vision",
  },
  {
    id: "grok-3",
    providerId: "xai",
    apiFormat: "openai-chat",
    modelId: "grok-3",
    displayName: "Grok 3",
    name: "Grok 3",
    description: "Grok 通用文本模型，作为通用模型分类中的额外跨厂商备选。",
    summary: "跨厂商通用文本备选",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.4,
    capabilities: ["通用问答", "结构化输出", "复杂解释"],
    capabilitySummary: ["跨厂商备选", "通用文本", "适合对比验证"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["通用文本问诊", "结构化建议", "跨模型对比"],
    sessionType: "text",
  },
  {
    id: "grok-4.1",
    providerId: "xai",
    apiFormat: "openai-chat",
    modelId: "grok-4.1",
    displayName: "Grok 4.1",
    name: "Grok 4.1",
    description: "当前中转链路下已实测可用的 xAI 高端文本模型，适合做国外高阶模型对照。",
    summary: "实测可用的 xAI 高端文本模型",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.8,
    capabilities: ["深度解释", "结构化输出", "复杂问答"],
    capabilitySummary: ["中文输出稳定", "当前链路实测可用", "高端对照模型"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["高端文本对照", "复杂病情解释", "国际模型展示"],
    sessionType: "text",
  },
  {
    id: "qwen3-vl-flash",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-flash",
    displayName: "Qwen 3 VL Flash",
    name: "Qwen 3 VL Flash",
    description: "当前默认图片模型，也是推荐的通用演示入口。",
    summary: "视觉理解优先推荐",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 5,
    capabilities: ["图片理解", "文本+图片", "低成本"],
    capabilitySummary: ["视觉首选", "响应快", "低成本"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["图片问诊", "图文联合", "低成本视觉场景"],
    sessionType: "vision",
    recommendedForImageHandoff: true,
  },
  {
    id: "qwen3-vl-plus",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-plus",
    displayName: "Qwen 3 VL Plus",
    name: "Qwen 3 VL Plus",
    description: "适合更复杂的图片理解与补充分析，不作为默认图片入口。",
    summary: "增强视觉分析",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.8,
    capabilities: ["图片理解", "细节分析", "复杂场景"],
    capabilitySummary: ["视觉更强", "复杂图更稳", "成本中等"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["复杂图片理解", "更高质量图文分析"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-32b-thinking",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-32b-thinking",
    displayName: "Qwen 3 VL 32B Thinking",
    name: "Qwen 3 VL 32B Thinking",
    description: "具备思考能力的视觉模型，适合图文推理。",
    summary: "视觉+思考",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.7,
    capabilities: ["视觉推理", "图文分析", "思考模式"],
    capabilitySummary: ["视觉思考", "推理强", "速度中等"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["图文推理", "复杂图片分析"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-235b-a22b-thinking",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-235b-a22b-thinking",
    displayName: "Qwen 3 VL 235B Thinking",
    name: "Qwen 3 VL 235B Thinking",
    description: "适合展示高阶视觉推理能力，但成本高、速度慢，不作为默认入口。",
    summary: "旗舰视觉推理",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.4,
    capabilities: ["旗舰视觉", "复杂推理", "高阶多模态"],
    capabilitySummary: ["旗舰视觉", "更强推理", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["高阶视觉问答", "复杂场景展示"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-32b-instruct",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-32b-instruct",
    displayName: "Qwen 3 VL 32B Instruct",
    name: "Qwen 3 VL 32B Instruct",
    description: "更均衡的视觉模型，适合图文问诊与常规图片理解。",
    summary: "均衡视觉问诊",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.7,
    capabilities: ["图片理解", "图文问答", "常规视觉分析"],
    capabilitySummary: ["更均衡", "图文兼顾", "适合常规视觉任务"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["图文问诊", "常规图片分析", "视觉备选"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-8b-instruct",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-8b-instruct",
    displayName: "Qwen 3 VL 8B Instruct",
    name: "Qwen 3 VL 8B Instruct",
    description: "轻量级视觉模型，适合快速检测和低成本图文问答。",
    summary: "轻量视觉备选",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 4.3,
    capabilities: ["图片理解", "低成本", "快速响应"],
    capabilitySummary: ["轻量", "速度快", "适合快速检测"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["快速图片检查", "低成本视觉备选", "轻量图文问答"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-30b-a3b-thinking",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-30b-a3b-thinking",
    displayName: "Qwen 3 VL 30B Thinking",
    name: "Qwen 3 VL 30B Thinking",
    description: "带思考模式的中高配视觉模型，适合图文推理。",
    summary: "视觉推理增强",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.6,
    capabilities: ["视觉推理", "图文分析", "思考模式"],
    capabilitySummary: ["图文推理更强", "速度适中", "适合复杂图片"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["复杂图片分析", "图文推理", "视觉对照测试"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-235b-a22b-instruct",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-235b-a22b-instruct",
    displayName: "Qwen 3 VL 235B Instruct",
    name: "Qwen 3 VL 235B Instruct",
    description: "旗舰视觉指令版，适合高质量图片理解与图文联合问答。",
    summary: "旗舰视觉指令版",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.7,
    capabilities: ["旗舰视觉", "图文问答", "高质量理解"],
    capabilitySummary: ["理解更细", "图文兼顾", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["高质量图文分析", "复杂图片问诊", "旗舰视觉展示"],
    sessionType: "vision",
  },
  {
    id: "gpt-4o-all",
    providerId: "openai",
    apiFormat: "openai-chat",
    modelId: "gpt-4o-all",
    displayName: "GPT-4o All",
    name: "GPT-4o All",
    description: "多模态通用模型，适合兼顾文本与图片理解。",
    summary: "多模态通用",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.6,
    capabilities: ["文本", "图片", "多模态问答"],
    capabilitySummary: ["多模态通用", "支持视觉", "国际模型"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["多模态通用", "品牌展示", "视觉问答"],
    sessionType: "vision",
  },
  {
    id: "claude-sonnet-4-6-vision",
    providerId: "anthropic",
    apiFormat: "anthropic-messages",
    modelId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6 Vision",
    name: "Claude Sonnet 4.6 Vision",
    description: "Anthropic 图文模型入口，适合做皮肤图片的跨厂商细节对比。",
    summary: "Anthropic 图文分析",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.5,
    capabilities: ["图文联合", "细节描述", "跨厂商对比"],
    capabilitySummary: ["Claude 视觉入口", "适合细节描述", "海外链路或代理更稳"],
    status: "unknown",
    latencyMs: null,
    networkHint: "需代理 / 海外链路更稳",
    recommendedUseCases: ["Claude 图文对比", "细节描述补充", "非千问视觉备选"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-30b-a3b-instruct",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-30b-a3b-instruct",
    displayName: "Qwen 3 VL 30B Instruct",
    name: "Qwen 3 VL 30B Instruct",
    description: "当前中转链路下实测可用的视觉模型，适合作为图片问诊稳定备选。",
    summary: "稳定视觉备选",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.6,
    capabilities: ["图片理解", "图文问答", "稳定视觉分析"],
    capabilitySummary: ["当前链路可用", "图文兼顾", "适合视觉备选"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["视觉备选", "图片问诊", "图文联合分析"],
    sessionType: "vision",
  },
  {
    id: "grok-4-fast-reasoning",
    providerId: "xai",
    apiFormat: "openai-chat",
    modelId: "grok-4-fast-reasoning",
    displayName: "Grok 4 Fast Reasoning",
    name: "Grok 4 Fast Reasoning",
    description: "当前中转链路下实测稳定可用的海外高端模型，兼顾速度和推理质量。",
    summary: "海外高端快速推理",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "high",
    recommendedScore: 4.8,
    capabilities: ["深度推理", "结构化输出", "复杂解释"],
    capabilitySummary: ["海外高端", "当前链路稳定", "速度比重推理模型更友好"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["深度推理", "高端展示", "复杂场景"],
    sessionType: "text",
  },
  {
    id: "gpt-5.4-nano",
    providerId: "openai",
    apiFormat: "openai-responses",
    modelId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    name: "GPT-5.4 Nano",
    description: "适合作为超低成本备用文本模型，不建议承担正式演示主流程。",
    summary: "低成本快速",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 4.1,
    capabilities: ["快速响应", "低成本", "轻量文本"],
    capabilitySummary: ["低成本", "快", "轻量"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["轻量问题", "低成本备用", "快速检测"],
    sessionType: "text",
  }
]
