export const curatedModels = [
  {
    id: "gpt-5.4-mini",
    providerId: "openai",
    apiFormat: "openai-chat",
    modelId: "gpt-5.4-mini",
    displayName: "GPT-5.4 mini",
    name: "GPT-5.4 mini",
    description: "高质量通用文本模型，适合作为默认工作模型。",
    summary: "通用文本与轻推理的平衡选择",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "medium",
    recommendedScore: 5,
    capabilities: ["通用问答", "代码", "内容整理"],
    capabilitySummary: ["通用任务平衡", "适合作为默认模型", "支持流式输出"],
    status: "unknown",
    latencyMs: null,
    networkHint: "待实测",
    recommendedUseCases: ["默认对话", "知识整理", "结构化问答"],
    sessionType: "text",
  },
  {
    id: "gpt-5.4",
    providerId: "openai",
    apiFormat: "openai-responses",
    modelId: "gpt-5.4",
    displayName: "GPT-5.4",
    name: "GPT-5.4",
    description: "高强度推理与高质量生成，走 Responses 格式。",
    summary: "深度推理优先",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 5,
    capabilities: ["深度推理", "复杂任务", "高质量生成"],
    capabilitySummary: ["Responses 格式", "复杂推理更强", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["复杂诊断建议整理", "高难度推理", "重点展示场景"],
    sessionType: "text",
  },
  {
    id: "qwen-plus-latest",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen-plus-latest",
    displayName: "Qwen Plus Latest",
    name: "Qwen Plus Latest",
    description: "中文综合能力稳、速度快、成本友好。",
    summary: "中文问答与整理的高性价比选择",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 5,
    capabilities: ["中文问答", "内容整理", "低成本"],
    capabilitySummary: ["中文友好", "速度快", "低成本"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["日常咨询", "低成本部署", "快速回复"],
    sessionType: "text",
  },
  {
    id: "qwen3.6-plus",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3.6-plus",
    displayName: "Qwen 3.6 Plus",
    name: "Qwen 3.6 Plus",
    description: "新一代通义文本模型，适合稳定的中文主力问答。",
    summary: "中文主力文本模型",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "medium",
    recommendedScore: 4.7,
    capabilities: ["中文理解", "长文整理", "通用推理"],
    capabilitySummary: ["中文主力", "稳定", "长文表现更均衡"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["主力中文聊天", "知识解释", "中等复杂任务"],
    sessionType: "text",
  },
  {
    id: "deepseek-chat",
    providerId: "deepseek",
    apiFormat: "openai-chat",
    modelId: "deepseek-chat",
    displayName: "DeepSeek Chat",
    name: "DeepSeek Chat",
    description: "通用文本模型，适合成本敏感的问答场景。",
    summary: "低成本通用文本",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 4.4,
    capabilities: ["通用问答", "低成本", "快速响应"],
    capabilitySummary: ["便宜", "快", "适合泛用"],
    status: "unknown",
    latencyMs: null,
    networkHint: "待实测",
    recommendedUseCases: ["成本敏感场景", "快速问答", "备用模型"],
    sessionType: "text",
  },
  {
    id: "deepseek-r1",
    providerId: "deepseek",
    apiFormat: "openai-chat",
    modelId: "deepseek-r1",
    displayName: "DeepSeek R1",
    name: "DeepSeek R1",
    description: "深度思考路线的代表模型，适合推理型问题。",
    summary: "深度推理与思考",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.8,
    capabilities: ["深度推理", "复杂分析", "思考型回答"],
    capabilitySummary: ["思考强", "复杂推理好", "速度中等"],
    status: "unknown",
    latencyMs: null,
    networkHint: "待实测",
    recommendedUseCases: ["复杂病情分析", "推理问题", "展示深度思考"],
    sessionType: "text",
  },
  {
    id: "claude-sonnet-4-6",
    providerId: "anthropic",
    apiFormat: "openai-chat",
    modelId: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    name: "Claude Sonnet 4.6",
    description: "高质量文本模型，兼顾稳定表达与复杂任务。",
    summary: "高质量综合文本",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.8,
    capabilities: ["复杂写作", "高质量表达", "推理"],
    capabilitySummary: ["高质量", "稳定", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["高质量对话", "展示性回答", "复杂解释"],
    sessionType: "text",
  },
  {
    id: "claude-opus-4-6-thinking",
    providerId: "anthropic",
    apiFormat: "anthropic-messages",
    modelId: "claude-opus-4-6-thinking",
    displayName: "Claude Opus 4.6 Thinking",
    name: "Claude Opus 4.6 Thinking",
    description: "Claude 原生思考版，走 messages 原生格式。",
    summary: "原生深度思考",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.9,
    capabilities: ["深度推理", "复杂任务", "长链思考"],
    capabilitySummary: ["messages 原生格式", "思考深", "成本高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["高难度分析", "深度展示", "复杂推理"],
    sessionType: "text",
  },
  {
    id: "qwen3-vl-flash",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-flash",
    displayName: "Qwen 3 VL Flash",
    name: "Qwen 3 VL Flash",
    description: "高性价比视觉模型，适合图片理解首选。",
    summary: "视觉理解优先推荐",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 5,
    capabilities: ["图片理解", "文本+图片", "低成本"],
    capabilitySummary: ["视觉首选", "响应快", "低成本"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["图片问诊", "图文联合", "低成本视觉场景"],
    sessionType: "vision",
    recommendedForImageHandoff: true,
  },
  {
    id: "qwen3-vl-plus",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-plus",
    displayName: "Qwen 3 VL Plus",
    name: "Qwen 3 VL Plus",
    description: "更强的通义视觉模型，适合更复杂图片理解。",
    summary: "增强视觉分析",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.8,
    capabilities: ["图片理解", "细节分析", "复杂场景"],
    capabilitySummary: ["视觉更强", "复杂图更稳", "成本中等"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["复杂图片理解", "更高质量图文分析"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-32b-thinking",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-32b-thinking",
    displayName: "Qwen 3 VL 32B Thinking",
    name: "Qwen 3 VL 32B Thinking",
    description: "具备思考能力的视觉模型，适合图文推理。",
    summary: "视觉+思考",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.7,
    capabilities: ["视觉推理", "图文分析", "思考模式"],
    capabilitySummary: ["视觉思考", "推理强", "速度中等"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["图文推理", "复杂图片分析"],
    sessionType: "vision",
  },
  {
    id: "qwen3-vl-235b-a22b-thinking",
    providerId: "qwen",
    apiFormat: "openai-chat",
    modelId: "qwen3-vl-235b-a22b-thinking",
    displayName: "Qwen 3 VL 235B Thinking",
    name: "Qwen 3 VL 235B Thinking",
    description: "高阶视觉推理模型，适合展示最强视觉理解。",
    summary: "旗舰视觉推理",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.8,
    capabilities: ["旗舰视觉", "复杂推理", "高阶多模态"],
    capabilitySummary: ["旗舰视觉", "更强推理", "成本较高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "国内直连优先",
    recommendedUseCases: ["高阶视觉问答", "复杂场景展示"],
    sessionType: "vision",
  },
  {
    id: "gpt-4o-all",
    providerId: "openai",
    apiFormat: "openai-chat",
    modelId: "gpt-4o-all",
    displayName: "GPT-4o All",
    name: "GPT-4o All",
    description: "多模态通用模型，适合兼顾文本与图片理解。",
    summary: "多模态通用",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "high",
    recommendedScore: 4.6,
    capabilities: ["文本", "图片", "多模态问答"],
    capabilitySummary: ["多模态通用", "支持视觉", "国际模型"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["多模态通用", "品牌展示", "视觉问答"],
    sessionType: "vision",
  },
  {
    id: "llama-3.2-90b-vision-instruct",
    providerId: "meta",
    apiFormat: "openai-chat",
    modelId: "llama-3.2-90b-vision-instruct",
    displayName: "Llama 3.2 90B Vision",
    name: "Llama 3.2 90B Vision",
    description: "开源系视觉大模型，适合作为视觉备选。",
    summary: "开源视觉备选",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "medium",
    priceLevel: "medium",
    recommendedScore: 4.3,
    capabilities: ["图片理解", "开源路线", "多模态问答"],
    capabilitySummary: ["开源视觉", "可作为备选", "兼顾成本"],
    status: "unknown",
    latencyMs: null,
    networkHint: "待实测",
    recommendedUseCases: ["视觉备选", "对照测试", "开源路线展示"],
    sessionType: "vision",
  },
  {
    id: "o3-pro-all",
    providerId: "openai",
    apiFormat: "openai-responses",
    modelId: "o3-pro-all",
    displayName: "o3 Pro All",
    name: "o3 Pro All",
    description: "高阶深度推理模型，适合复杂链路推理展示。",
    summary: "高阶推理",
    supportsVision: true,
    supportsStreaming: true,
    speedLevel: "slow",
    priceLevel: "high",
    recommendedScore: 4.7,
    capabilities: ["深度推理", "多步分析", "高质量输出"],
    capabilitySummary: ["Responses 路线", "推理强", "成本高"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["深度推理", "高端展示", "复杂场景"],
    sessionType: "text",
  },
  {
    id: "gpt-5.4-nano",
    providerId: "openai",
    apiFormat: "openai-chat",
    modelId: "gpt-5.4-nano",
    displayName: "GPT-5.4 Nano",
    name: "GPT-5.4 Nano",
    description: "低成本快速文本模型，适合轻量任务和备用方案。",
    summary: "低成本快速",
    supportsVision: false,
    supportsStreaming: true,
    speedLevel: "fast",
    priceLevel: "low",
    recommendedScore: 4.1,
    capabilities: ["快速响应", "低成本", "轻量文本"],
    capabilitySummary: ["低成本", "快", "轻量"],
    status: "unknown",
    latencyMs: null,
    networkHint: "海外网络更稳",
    recommendedUseCases: ["轻量问题", "低成本备用", "快速检测"],
    sessionType: "text",
  }
]
